### ISSUE TITLE
requirement on renewalparam

### ISSUE THREAD

**Issue by switit** [raforg/danectl#14] opened 2024-02-10 03:10 UTC
For this to work, 

` reuse_key = True`

is needed under renewalparams. Is that the correct understanding? If so, please specify that in the readme.md.
Regards,
Witit

**Comment by raforg** [comment] 2024-02-11 02:24
Hi, That is the correct understanding. And that is why *danectl* adds `reuse_key = True` to the `[renewalparams]` if it is not already there when adopting an existing certificate lineage. It also makes sure that it is present when creating new certificate lineages. It also makes sure that it is present for the next certificate when doing a rollover (in case it has been manually removed). Also, just in case it is manually removed at any point, whenever the `tlsa-check` (or `check`) command is used without arguments, and whenever the `status` command is used, its presence is checked for and fixed if wrong.

That is why I don't think that it needs to be mentioned in the readme. The software handles it itself. The user shouldn't really need to know this implementation detail. Have you encountered a situation where the above is not working as intended? Or do you just think it's important to make sure that the user is aware of it? If it's the latter, the readme does state:

    After that, certbot automatically renews both certificates every few months,
    but the underlying keys won't change, and the TLSA records (see below)
    can remain stable.

I think that's the best way to make it clear to users that the keys are being reused across certificate renewals. Explaining how the key reuse is implemented is a job for *certbot*'s documentation. However, the *certbot* team have explicitly decided not to document the format of their configuration files, presumably because they want to discourage direct manipulation of them. They reserve the right to alter the format should the need arise. So I don't think they would appreciate other software documenting their format.

This is why the manual entry explains the behaviour in terms of *certbot*'s documented `--reuse-key` command line option, rather than in terms of its undocumented `reuse_key` renewal parameter:

    To check that all TLSA records for the current and next keys are correctly
    published in the DNS:

      danectl tlsa-check example.org

    If no cert-name is supplied, then all cert-names are checked, and the
    --reuse-key status of each certificate lineage is checked, and restored if
    it is unset for any reason.

and:

    At any time, you can show the status of all certificate pairs:

      danectl status

    [...]

    If any of the certificate lineages no longer have their --reuse-key status
    set for any reason, this is also mentioned, and it is restored.

So, if the user is unaware of this requirement, and does manually remove `reuse_key = True` from the configuration file(s), it will be fixed automatically the next time they `check` the TLSA records (hopefully daily via *cron*).

**Comment by switit** [comment] 2024-02-12 03:23
Thank you for your explanation in great details. I did not realize cerbot has --reuse-key option until recently when I started to work on automating the dane dnssec renewal process. I still think it will help people like me if you explain explicitly about --reuse-key, atleast for the peace of mine.
Cheers,
Witit

**Closed as completed** 2024-02-24 05:10 UTC
